In [1]:
import numpy as np
import copy
import cv2
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
from PIL import Image
from keras import models
from tensorflow.keras.utils import img_to_array
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import confusion_matrix
import os

In [2]:
model = models.load_model('mug2c.h5')
class_names  = {0: "mug", 1: "nomug"}
video = cv2.VideoCapture(0)

In [3]:
while True:
        _, frame = video.read()

        #Convert the captured frame into RGB
        im = Image.fromarray(frame, 'RGB')

        #Resizing into dimensions you used while training
        im = im.resize((224,224))
       
        
        img_array = np.array(im)
       # x,y,w = img_array.shape
        #roi_gray = gray[y:y + h, x:x + w]
        #roi_color =img[y:y + h, x:x + w]
        
        #Expand dimensions to match the 4D Tensor shape.
        img_array = np.expand_dims(img_array, axis=0)
    
        #Calling the predict function using keras
        prediction = model.predict(img_array)#[0][0]
        mug = tf.nn.sigmoid(prediction[0])
        names=class_names[np.argmax(mug)]
        print(prediction)
        
        #Customize this part to your liking...
        
                     
        if(prediction[0][1]>0.5):
            print(names)
        elif(prediction[0][0]>0.5):
            print(names)

        cv2.imshow("Prediction", frame)
        key=cv2.waitKey(1)
        if key == 27:
            print('esc is pressed closing all windows')
            cv2.destroyAllWindows()
            break
        
    
               
if cv2.getWindowProperty('sunset', cv2.WND_PROP_VISIBLE) < 1:
    print("ALL WINDOWS ARE CLOSED")
cv2.waitKey(0)
cv2.destroyAllWindows()       


1/1 [==============================] - 0s 194ms/step
[[ 1.7864245 -1.9158154]]
mug
1/1 [==============================] - 0s 38ms/step
[[ 1.7595619 -1.8842825]]
mug
1/1 [==============================] - 0s 35ms/step
[[ 1.7526982 -1.8767363]]
mug
1/1 [==============================] - 0s 37ms/step
[[ 1.721644  -1.8484387]]
mug
1/1 [==============================] - 0s 36ms/step
[[ 1.7165779 -1.8442537]]
mug
1/1 [==============================] - 0s 43ms/step
[[ 1.6885247 -1.8206457]]
mug
1/1 [==============================] - 0s 36ms/step
[[ 1.6384687 -1.7744077]]
mug
1/1 [==============================] - 0s 31ms/step
[[ 1.6231246 -1.7585316]]
mug
1/1 [==============================] - 0s 39ms/step
[[ 1.6146036 -1.750716 ]]
mug
1/1 [==============================] - 0s 39ms/step
[[ 1.5868367 -1.7257526]]
mug
1/1 [==============================] - 0s 34ms/step
[[ 1.5805763 -1.7199465]]
mug
1/1 [==============================] - 0s 39ms/step
[[ 1.5620358 -1.7030457]]
mug
1/1 [==========